
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./iac/terraform/app/"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./iac/terraform/aws-services/"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./iac/terraform/admin-tenant/"]
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./iac/terraform/admin-infra/"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.74.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      # - id: terraform_tfsec
      - id: terraform_checkov
        args:
          - --args=--skip-check CKV_DOCKER_3
          - --args=--skip-check CKV_DOCKER_2
          - --args=--skip-check CKV_DOCKER_9
          - --args=--skip-check CKV_DOCKER_11
          - --args=--skip-check CKV_DOCKER_7
          - --args=--skip-check CKV_DOCKER_5
          - --args=--skip-check CKV_DOCKER_10
          - --args=--skip-check CKV_DOCKER_1
          - --args=--skip-check CKV_TF_1

